version: '3.8'
services:
  user_service:
    build:
      context: ./services/user_service
    ports:
      - "8000:8000"
    volumes:
      - ./services/user_service:/app
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  learning_service:
    build:
      context: ./services/learning_service
    ports:
      - "8001:8001"
    volumes:
      - ./services/learning_service:/app
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  assessment_service:
    build:
      context: ./services/assessment_service
    ports:
      - "8002:8002"
    volumes:
      - ./services/assessment_service:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - user_service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres
    environment:
      POSTGRES_USER: upskill_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: upskill_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"] 
    restart: always


volumes:
  postgres_data:


