version: '3.8'

services:
  user_service:
    build:
      context: ./services/user_service
    ports:
      - "8000:8000"
    volumes:
      - ./services/user_service:/app
    depends_on:
      - db
      - redis
      - auth_service
    env_file:
      - .env
    networks:
      - app_network
    restart: always

  learning_service:
    build:
      context: ./services/learning_service
    ports:
      - "8001:8001"
    volumes:
      - ./services/learning_service:/app
    depends_on:
      - db
      - redis
      - user_service
      - auth_service
    env_file:
      - .env
    networks:
      - app_network
    restart: always

  assessment_service:
    build:
      context: ./services/assessment_service
    ports:
      - "8002:8002"
    volumes:
      - ./services/assessment_service:/app
    depends_on:
      - db
      - redis
      - user_service
      - auth_service
    env_file:
      - .env
    networks:
      - app_network
    restart: always

  auth_service:
    build:
      context: ./services/authentication_service
    ports:
      - "8003:8003"
    volumes:
      - ./services/authentication_service:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network
    restart: always

  gateway_service:
    build:
      context: ./services/gateway_service
    ports:
      - "8080:8080"
    volumes:
      - ./services/gateway_service:/app
    depends_on:
      - user_service
      - learning_service
      - assessment_service
      - auth_service
    environment:
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - LEARNING_SERVICE_URL=${LEARNING_SERVICE_URL}
      - ASSESSMENT_SERVICE_URL=${ASSESSMENT_SERVICE_URL}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - GATEWAY_SERVICE_URL=${GATEWAY_SERVICE_URL}
    env_file:
      - .env
    networks:
      - app_network
    restart: always
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - app_network
    restart: always
  frontend:
    build:
      context: ./services/frontend
    ports:
      - "3000:80"
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://gateway_service:8080
    depends_on:
      - gateway_service
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
